spring:
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update


  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myDataBase
    initialization-mode: always

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  tomcat:
    uri-encoding: UTF-8

